name: Deploy Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pr-preview
      url: ${{ steps.deployment.outputs.preview_url }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Deployment
        id: deployment
        uses: bobheadxi/deployments@v1
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: pr-preview
          ref: ${{ github.head_ref }}
          no_override: false

      - name: Deploy Branch Preview
        id: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
          target-folder: pr-${{ github.event.pull_request.number }}

      - name: Update Deployment Status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: pr-preview
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://${{ github.repository_owner }}.github.io/claude-haiku/pr-${{ github.event.pull_request.number }}/
